# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Loki
    # <string, required> datasource type. Required
    type: loki
    # <string> Sets a custom UID to reference this data source in other parts of the configuration. If not specified, Grafana generates one.
    uid: loki
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string> url
    url: http://loki-gateway:8080
    # <bool> mark as default datasource. Max one per org
    isDefault: false
    version: 1
    # Loki data
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        # - datasourceUid: my_jaeger_uid
        #   matcherRegex: "traceID=(\\w+)"
        #   name: TraceID
        #   # url will be interpreted as query for the datasource
        #   url: '$${__value.raw}'
        # Field with external link.
        # - matcherRegex: "traceID=(\\w+)"
        #   name: TraceID
        #   url: 'http://localhost:16686/trace/$${__value.raw}'
        - datasourceUid: tempo
          matcherRegex: (?:trace_id)=(\w+)
          name: TraceIDFmt
          url: $${__value.raw}
        - datasourceUid: tempo
          matcherRegex: '"(?:trace_id)"\s*:\s*"(\w+)"'
          name: TraceIDJson
          url: $${__value.raw}
