{
 "title": "Python Webserver Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job name", "query": { "query": "label_values(python_info, job)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(http_requests_total{job=~\"$job\"}, handler)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(http_requests_total{job=~\"$job\", handler=~\"$handler\"}, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{job=~\"$job\"}",
     "legendFormat": "{{ implementation }} {{ version }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Virtual memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"$job\", handler=~\"$handler\", status=~\"$status\"}[$interval])) by (method, handler, status)",
     "legendFormat": "{{ method }} {{ handler }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Requests Total $handler",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=~\"$job\", handler=~\"$handler\"}[$__range])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_highr_seconds_bucket{job=~\"$job\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Duration $handler",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{job=~\"$job\", handler=~\"$handler\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{job=~\"$job\", handler=~\"$handler\"}[$interval])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{job=~\"$job\", handler=~\"$handler\"}[$interval]) / rate(http_request_duration_seconds_count{job=~\"$job\", handler=~\"$handler\"}[$interval])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum{job=~\"$job\", handler=~\"$handler\"}[$interval])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"} / process_max_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{service=\"$job\"} |~ \"\\\" [4-5][0-9][0-9]\\\"\" | json |  line_format \"{{.event}}\""
    }
   ]
  }
 ]
}