{
 "title": "Traefik Official Standalone Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_open_connections, entrypoint)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_open_connections, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[1m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[5m])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\",protocol=\"http\"}[1m])) by (method, code)",
     "legendFormat": "{{method}} [{{code}}]"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  traefik_service_request_duration_seconds_sum{service=~\"$service\",protocol=\"http\"}\n  /\n  traefik_service_request_duration_seconds_count{service=~\"$service\",protocol=\"http\"}\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Most requested services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum(rate(traefik_service_requests_total{service=~\"$service\",protocol=\"http\"}[5m])) by (service,code)  > 0)",
     "legendFormat": "[{{code}}] on {{service}}"
    }
   ]
  },
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Services failing SLO of 1200ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum(\n    rate(traefik_service_request_duration_seconds_bucket{le=\"1.2\",service=~\"$service\"}[5m])\n  ) by (service) \n  / \n  sum(\n    rate(traefik_service_request_duration_seconds_count{service=~\"$service\"}[5m])\n  ) by (service) \n) > 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services failing SLO of 300ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum(\n    rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",service=~\"$service.*\"}[5m])\n  ) by (service)\n  /\n  sum(\n    rate(traefik_service_request_duration_seconds_count{service=~\"$service.*\"}[5m])\n  ) by (service)\n) > 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "2xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum(\n    rate(traefik_service_requests_total{service=~\"$service\",code=~\"2..\",protocol=\"http\"}[5m])\n  ) by (service,method,code) > 0\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum(\n    rate(traefik_service_requests_total{service=~\"$service\",code=~\"5..\",protocol=\"http\"}[5m])\n  ) by (service,method,code) > 0\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum(\n    rate(traefik_service_requests_bytes_total{service=~\"$service\",protocol=\"http\"}[1m])\n  ) by (service,method) > 0\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum(\n    rate(traefik_service_responses_bytes_total{service=~\"$service\",protocol=\"http\"}[1m])\n  ) by (service,method) > 0\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=~\"$service\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{entrypoint=~\"$entrypoint\"}) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Other codes over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum(\n    rate(traefik_service_requests_total{service=~\"$service.*\",code!~\"2..|5..\",protocol=\"http\"}[5m])\n  ) by (service,method,code)  > 0\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  }
 ]
}